version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: couchsurfing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"

volumes:
  postgres-db:
    driver: local

    # if mysql stuck, "sudo pkill mysqld" stops mysql running in the background