version: "3.9"
services:
  mysql-server:
    image: mysql:8.0
    container_name: couchsuring_db
    command: --sql-mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      DATABASES: couchsurfing_db
    ports:
      - "3306:3306"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "couchsurfing-mysqldb:/var/lib/mysql"
volumes:
  couchsurfing-mysqldb: