version: "3.9"
services:
  mysql-server:
    image: mysql:latest
    container_name: couchsurfing_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      DATABASES: couchsurfing_db
    ports:
      - "3306:3306"
    volumes:
      - "couchsurfing-mysqldb:/var/lib/mysql"
volumes:
  couchsurfing-mysqldb: